version: "2"
name: Test_website 2
canonical: test_website_2
author: Julie Horville
status: private
description: Test
image: ""
keywords:
- website
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      test_website_2:
        destination: ($ project $)/default/terraform/($ environment $)/test_website_2.tf
        path: default/terraform/test_website_2.tf.sample
