version: "2"
use_cases:
- name: default
  sections:
  - name: Regional Settings
    groups:
    - name: Region
      technologies: [pipeline]
      vars:
      - name: Region
        description: In which region do you want to deploy ?
        key: region
        widget: dropdown
        type: string
        values: ["AME", "EMEA", "PAC"]
    - name: PAC Backup policy
      technologies: [pipeline]
      condition: $region == "PAC"
      vars:
      - name: "Subscription"
        description: In which subscription do you want to deploy ?
        key: subscription_pac
        widget: dropdown
        type: string
        values: ["PROD", "UAT"]
    - name: "PRW-PROD / Prod VM backup Policies"
      technologies: [pipeline]
      condition: $subscription_pac == "PROD"
      #condition: $region == "PAC" && $subscription_pac == "PROD"
      vars:
      - name: Backup Policies
        description: "Those are short backup policies. It means that the retention of the daily backups is between 15 and 30 days."
        key: backup_policy_prod_prod_vm_pac
        type: string
        widget: dropdown
        values: 
        - "VM-PROD-14D"
        - "VM-PROD-2Y"
        - "VM-PROD-3M"
        - "VM-PROD-7Y"
    - name: "PRW-PROD / Prod Databse backup Policies"
      technologies: [pipeline]
      condition: $subscription_pac == "UAT"
      #condition: $region == "PAC" && $subscription_pac == "UAT"
      vars:
      - name: Backup Policies
        description: "Those are short backup policies. It means that the retention of the daily backups is between 15 and 30 days."
        key: backup_policy_prod_prod_dbs_pac
        type: string
        widget: dropdown
        values: 
        - "SQL-PROD-3M"
        - "SQL-PROD-2Y"
        - "SQL-PROD-7Y"
