version: "2"
use_cases:
- name: default
  sections:
  - name: Common Informations
    groups:
    - name: Common Informations
      technologies: [pipeline]
      vars:
      - name: "Role"
        description: Server Role
        key: server_role
        widget: dropdown
        type: string
        values: ["APP", "WEB", "DBS", "TST", "JDE", "CTX"]
      - name: "Environment"
        description: "In which environment does the VM will be deploy ?"
        key: environment
        widget: dropdown
        type: string
        values: ["dev", "prod", "uat"]
  - name: Regional Settings
    groups:
    - name: Region
      technologies: [pipeline]
      vars:
      - name: Region
        description: In which region do you want to deploy ?
        key: region
        widget: dropdown
        type: string
        values: ["AME", "ASIA", "EMEA", "PAC"]
      - widget: dropdown
        values:
          options:
            - condition: $region == "AME"
              values: ["CAN", "USA", "TRU", "USW", "MEX", "PER", "VEN", "ARG", "BRA", "CHL", "URY", "COL", "DOM", "CSW", "HWS", "GLB"]
            - condition: $region == "ASIA"
              values: ["CHN", "AHQ", "TRA", "JPN", "KOR", "TWN", "THA", "HKG", "PHL", "GLB"]
            - condition: $region == "EMEA"
              values: ["MEA", "FRA", "GLB", "MMP", "ZAF", "SVN", "ESP", "PWS", "TUR", "GRC"]
            - condition: $region == "PAC"
              values: ["AUS", "NZL", "ANZ", "GLB"]
        type: string
        key: affiliate
        name: Affiliate Choice
        description: "In which affiliate do you want to deploy your Virtual Machine ?"
    - name: EMEA Settings 
      technologies: [pipeline]
      condition: $region == "EMEA"
      vars:
      - name: EMEA Backup Policy
        description: "Which type of retention do you want to use for the backup storage ?"
        key: retention
        widget: dropdown
        type: string
        values: ["Short", "Medium", "Long"]
      - name: EMEA Backup Policies
        description: "Which backup policy do you want to use ?"
        key: backup_policy
        widget: dropdown
        type: string
        values:
          options:
            - condition: $retention == "Short"
              values: ["15 daily at 4 AM", "15 daily at 5 PM", "30 daily at 6 AM", "30 daily at 4 PM"]
            - condition: $retention == "Medium"
              values: ["15 daily, 6 monthly at 2:30 AM", "15 daily, 6 monthly at 4 PM", "30 daily, 6 monthly at 3:30 AM", "30 daily, 6 monthly at 7 PM", "15 daily, 13 monthly at 3 AM", "30 daily, 13 monthly at 5:30 AM", "30 daily, 13 monthly at 8 PM"]
            - condition: $retention == "Long"
              values: ["30 daily, 13 monthly, 3 yearly at midnight", "30 daily, 13 monthly, 5 yearly at 9 PM", "30 daily, 13 monthly, 10 yearly at 1 AM", "30 daily, 13 monthly, 10 yearly at 10:30 PM", "60 daily, 13 monthly, 10 yearly at 10 PM"] 
    - name: PAC Backup policy
      technologies: [pipeline]
      condition: $region == "PAC"
      vars:
      - name: "Subscription"
        description: In which subscription do you want to deploy ?
        key: subscription_pac
        widget: dropdown
        type: string
        values: ["PRW-PROD", "PRW-UAT"]
    - name: "PRW-PROD / Prod VM backup Policies"
      technologies: [pipeline]
      condition: (($region == "PAC" && $subscription_pac == "PRW-PROD" && $environment == "prod") && ($server_role == "APP" || $server_role == "WEB" || $server_role == "TST"))
      vars:
      - name: Backup Policies
        description: "Those are short backup policies. It means that the retention of the daily backups is between 15 and 30 days."
        key: backup_policy_prod_prod_vm_pac
        type: string
        widget: dropdown
        values: 
        - "VM-PROD-14D"
        - "VM-PROD-2Y"
        - "VM-PROD-3M"
        - "VM-PROD-7Y"
    - name: "PRW-PROD / Prod Databse backup Policies"
      technologies: [pipeline]
      condition: (($region == "PAC" && $subscription_pac == "PRW-PROD" && $environment == "prod" && $server_role == "DBS"))
      vars:
      - name: Backup Policies
        description: "Those are short backup policies. It means that the retention of the daily backups is between 15 and 30 days."
        key: backup_policy_prod_prod_dbs_pac
        type: string
        widget: dropdown
        values: 
        - "SQL-PROD-3M"
        - "SQL-PROD-2Y"
        - "SQL-PROD-7Y"
    - name: "PRW-PROD / DEV/UAT VM Backup policies"
      technologies: [pipeline]
      condition: (($region == "PAC" && $subscription_pac == "PRW-PROD") && ($environment == "uat" || $environment == "dev") && ($server_role == "APP" || $server_role == "WEB" || $server_role == "TST"))
      vars:
      - name: Backup Policies
        description: "Those are medium backup policies. It means that you can chose the retention of the daily backup and the monthly backups."
        key: backup_policy_prod_uat_vm_pac
        type: string
        widget: dropdown
        values: 
        - "VM-UA"
        - "VM-UA-3M"
    - name: "PRW-PROD / DEV/UAT Database Backup policies"
      technologies: [pipeline]
      condition: (($region == "PAC" && $subscription_pac == "PRW-PROD") && ($environment == "uat" || $environment == "dev" && $server_role == "DBS"))
      vars:
      - name: Backup Policies
        description: "Those are medium backup policies. It means that you can chose the retention of the daily backup and the monthly backups."
        key: backup_policy_prod_uat_sql_pac
        type: string
        widget: dropdown
        values: 
        - "SQL-UA"
        - "SQL-UA"
        default: "SQL-UA"
    - name: "PRW-UAT / Prod VM Backup policies"
      technologies: [pipeline]
      condition: (($region == "PAC" && $subscription_pac == "PRW-UAT" && $environment == "prod") && ($server_role == "APP" || $server_role == "WEB" || $server_role == "TST"))
      vars:
      - name: Backup Policies
        description: "Those are medium backup policies. It means that you can chose the retention of the daily backup and the monthly backups."
        key: backup_policy_uat_prod_vm_pac
        type: string
        widget: dropdown
        values: 
        - "VM-PROD-7Y"
        - "VM-PROD-3M"
        - "VM-PROD-14D"
        - "VM-PROD-2Y"
    - name: "PRW-UAT / Prod Database backup Policies"
      technologies: [pipeline]
      condition: $region == "PAC" && $subscription_pac == "PRW-UAT" && $environment == "prod" && $server_role == "DBS"
      vars:
      - name: Backup Policies
        description: "Those are short backup policies. It means that the retention of the daily backups is between 15 and 30 days."
        key: backup_policy_uat_prod_sql_pac
        type: string
        widget: dropdown
        values: 
        - "SQL-PROD-2Y"
        - "SQL-PROD-7Y"
        - "SQL-PROD-3M"
    - name: "PRW-UAT / DEV/UAT VM Backup policies"
      technologies: [pipeline]
      condition: (($region == "PAC" && $subscription_pac == "PRW-UAT") && ($environment == "uat" || $environment == "dev") && ($server_role == "APP" || $server_role == "WEB" || $server_role == "TST"))
      vars:
      - name: Backup Policies
        description: "Those are medium backup policies. It means that you can chose the retention of the daily backup and the monthly backups."
        key: backup_policy_uat_uat_vm_pac
        type: string
        widget: dropdown
        values:
        - "VM-UA"
        - "VM-UA"
        default: "VM-UA"
    - name: "PRW-UAT / UAT Database Backup policies"
      technologies: [pipeline]
      condition: (($region == "PAC" && $subscription_pac == "PRW-UAT") && ($environment == "uat" || $environment == "dev") && ($server_role == "DBS"))
      vars:
      - name: Backup Policies
        description: "Those are medium backup policies. It means that you can chose the retention of the daily backup and the monthly backups."
        key: backup_policy_uat_uat_sql_pac
        type: string
        widget: dropdown
        values: 
        - "SQL-UA"
        - "SQL-UA"
        default: "SQL-UA"
