version: "2"
use_cases:
- name: default
  sections:
  - name: Regional Settings
    groups:
    - name: Region
      technologies: [pipeline]
      vars:
      - name: Region
        description: In which region do you want to deploy ?
        key: region
        widget: dropdown
        type: string
        values: ["AME", "EMEA", "PAC"]
    - name: EMEA Settings 
      technologies: [pipeline]
      condition: $region == "EMEA"
      vars:
      - name: EMEA Backup Policy
        description: "Which type of retention do you want to use for the backup storage ?"
        key: retention
        widget: dropdown
        type: string
        values: ["Short", "Medium", "Long"]
      - name: EMEA Backup Policies
        description: "Which backup policy do you want to use ?"
        key: backup_policy
        widget: dropdown
        type: string
        values:
          options:
            - condition: $retention == "Short"
              values: ["15 daily at 4 AM", "15 daily at 5 PM", "30 daily at 6 AM", "30 daily at 4 PM"]
            - condition: $retention == "Medium"
              values: ["15 daily, 6 monthly at 2:30 AM", "15 daily, 6 monthly at 4 PM", "30 daily, 6 monthly at 3:30 AM", "30 daily, 6 monthly at 7 PM", "15 daily, 13 monthly at 3 AM", "30 daily, 13 monthly at 5:30 AM", "30 daily, 13 monthly at 8 PM"]
            - condition: $retention == "Long"
              values: ["30 daily, 13 monthly, 3 yearly at midnight", "30 daily, 13 monthly, 5 yearly at 9 PM", "30 daily, 13 monthly, 10 yearly at 1 AM", "30 daily, 13 monthly, 10 yearly at 10:30 PM", "60 daily, 13 monthly, 10 yearly at 10 PM"] 
    - name: PAC Backup policy
      technologies: [pipeline]
      condition: $region == "PAC"
      vars:
      - name: "Subscription"
        description: In which subscription do you want to deploy ?
        key: subscription_pac
        widget: dropdown
        type: string
        values: ["PROD", "UAT"]
    - name: "PRW-PROD / Prod VM backup Policies"
      technologies: [pipeline]
      condition: $region == "PAC" && $subscription_pac == "PROD"
      vars:
      - name: Backup Policies
        description: "Those are short backup policies. It means that the retention of the daily backups is between 15 and 30 days."
        key: backup_policy_prod_prod_vm_pac
        type: string
        widget: dropdown
        values: 
        - "VM-PROD-14D"
        - "VM-PROD-2Y"
        - "VM-PROD-3M"
        - "VM-PROD-7Y"
    - name: "PRW-PROD / Prod Databse backup Policies"
      technologies: [pipeline]
      condition: $region == "PAC" && $subscription_pac == "UAT"
      vars:
      - name: Backup Policies
        description: "Those are short backup policies. It means that the retention of the daily backups is between 15 and 30 days."
        key: backup_policy_prod_prod_dbs_pac
        type: string
        widget: dropdown
        values: 
        - "SQL-PROD-3M"
        - "SQL-PROD-2Y"
        - "SQL-PROD-7Y"
