---
version: 2
use_cases:
  - name: windows
    sections:

      - name: Terraform
        groups:
          - name: Servers Network Type
            technologies: [pipeline,terraform]
            vars:
              - name: mdc
                description: Do you need a MDC VRF ?
                key: mdc
                widget: switch
                type: boolean
                default: False

          - name: Servers Network Suffix
            technologies: [pipeline]
            condition: "$mdc == true"
            vars:
              - name: VRF's suffix
                description: Select VRF suffix
                key: suffix
                widget: dropdown
                type: map
                values:
                  - {"label": "Devant", "value": "1"}
                  - {"label": "Derriere", "value": "2"}
                  - {"label": "Agent", "value": "3"}     

          - name: VM Type
            technologies: [terraform,pipeline]
            vars:
              - name: VM Type
                description: What type of VM do you need ?
                key: vmtype
                widget: dropdown
                type: string
                default: 'Normal'
                values:
                  - 'Normal'
                  - 'Monster'
                  - 'Anormal'
                required: true

          - name: VM 
            #technologies: [pipeline] 
            #technologies: [terraform]
            technologies: [terraform,pipeline] 
            vars: 
              - name: Cluster Name 
                description: Select Cluster 
                key: cluster_name 
                widget: dropdown 
                type: map
                #default: 
                #  options: 
                #    - name: Normal VM 
                #      condition: "$vmtype == 'Normal'" 
                #      default: "1"
                #    - name: Monster VM 
                #      condition: "$vmtype == 'Monster'" 
                #      default: "7"
                values: 
                  options: 
                    - name: Normal VM 
                      condition: "$vmtype == 'Normal'" 
                      values: 
                        - {"label":"a",        "value":"1"} 
                        - {"label":"b",        "value":"2"} 
                        - {"label":"c",          "value":"3"} 
                        - {"label":"d",       "value":"4"} 
                        - {"label":"e",       "value":"5"} 
                        - {"label":"f",     "value":"6"} 
                    - name: Monster VM 
                      condition: "$vmtype == 'Monster'" 
                      values: 
                        - {"label":"g",          "value":"7"} 
                        - {"label":"h",          "value":"8"} 

                  
  - name: linux
    sections:
      - name: Commons
        groups:
          - name: Servers Parameters
            technologies: [pipeline]
            vars:
              - name: Servers names
                key: list_server
                type: string
                widget: simple_text
                description: Enter the NAME(s) separated by a comma
                required: true
