version: "2"
use_cases:
- name: default
  sections:
  - name: General
    groups:
    - name: InstanceA
      technologies: [terraform]
      vars:
        - name: "count"
          description: "Number of Aws EC2 onprem server to create."
          key: instance_a_count
          widget: number
          type: integer
          default: 1

        - name: "type auto_complete/string"
          description: "Type of Aws EC2 onprem servers. (micro missing)"
          key: instance_a_type
          # auto_complete not compatible for now. We choose to not allow it
          # widget: auto_complete
          widget: dropdown
          type: string
          default: "t3.small"
          values:
              - "t3.small"
              - "t3.medium"
              - "t3.large"
          quota_config:
            count_ref: instance_a_count
            mapping:
              "t3.small": "1 cpu, 2048 memory"
              "t3.medium": "2 cpu, 4096 memory"
              "t3.large": "4 cpu, 8192 memory"

        - name: "disk size"
          unit: Go
          description: "Disk size of Aws EC2 onprem servers."
          key: instance_a_disk_size
          widget: slider_range
          type: integer
          default: 60
          values:
              - 10
              - 500
          quota_config:
            count_ref: instance_a_count
            type: "storage"

    - name: InstanceB
      technologies: [terraform]
      vars:
        - name: "CPU"
          description: "Number of Aws EC2 onprem server to create."
          key: instance_b_cpu
          widget: number
          type: integer
          default: 1
          quota_config:
            type: "cpu"

        - name: "MEM Mo"
          description: "Type of Aws EC2 onprem servers."
          key: instance_b_memory
          widget: radios
          type: map
          default: "128m"
          values:
              - {label: "128m", value: 128}
              - {label: "256m", value: 256}
              - {label: "512m", value: 512}
          quota_config:
            type: "memory"

        # comment since it doesn't works
        # The Forms File has an invalid format: use case "default" invalid definition for variable "instance_b_disk_size" (key) in section "General" of "InstanceB": The Forms Entity has an invalid format: invalid quota mapping, key "S" is not a value on the entity
        - name: "disk size type mapping"
          unit: Go
          description: "Disk size of Aws EC2 onprem servers. (**S** 10G, **M** 50G, **L** 100G)"
          key: instance_b_disk_size
          widget: radios
          type: map
          default: "S"
          values:
              - {label: S, value: 10}
              - {label: M, value: 50}
              - {label: L, value: 100}
          quota_config:
            mapping:
              10: "10 storage"
              50: "50 storage"
              100: "100 storage"

    - name: InstanceC
      technologies: [terraform]
      vars:
        - name: "type auto_complete/string"
          description: "Type of Aws EC2 onprem servers"
          key: instance_c_type
          widget: dropdown
          type: string
          default: "r5.large"
          values:
              - "r5.large"
              - "r5.xlarge"
              - "r5.2xlarge"
          quota_config:
            mapping:
              "r5.large": "1 cpu, 1024 memory, 10 storage"
              "r5.xlarge": "2 cpu, 2048 memory, 50 storage"
              "r5.2xlarge": "4 cpu, 4096 memory, 100 storage"


    - name: InstanceDynamic
      technologies: [terraform]
      vars:
        - name: Env
          default: dev
          description: Dict of extra tags to add to the vm instance.
          key: instance_d_env
          mismatch_values:
          type: string
          values:
          - "dev"
          - "prod"
          widget: dropdown
        - name: Vm type
          description: Type of instance to use for the instance.
          key: instance_d_type
          mismatch_values:
          required: true
          type: map
          default: "M"
          values:
            options:
              - name: "Dev instance types"     # optional a name to appy to this option
                condition: "$instance_d_env == 'dev'"     # Condition to respect to have the following values
                values:                        # The values to apply
                  - {"label": "XS", "value": "t2.nano"}
                  - {"label": "S", "value": "t2.small"}
                  - {"label": "M", "value": "t2.medium"}
              - name: "Prod instance types"
                condition: "$instance_d_env == 'prod'"
                values:
                  - {"label": "M", "value": "t2.medium"}
                  - {"label": "L", "value": "t2.large"}
          widget: radios
          quota_config:
           mapping:
             "t2.nano": "1 cpu, 512 memory"
             "t2.small": "2 cpu, 2048 memory"
             "t2.medium": "3 cpu, 4096 memory"
             "t2.large": "4 cpu, 8192 memory"
