---
version: '2'
name: Cycloid stack forms v2 (florian)
canonical: cycloid-forms-v2-florian
description: |
  Used to validate forms v2
keywords:
  - formsv2
  - forms
  - cycloid
  - stack
  - stacks
author: Cycloid
image: https://www.cycloid.io/themes/cycloid/images/owl_logo.png

config:
  default:
    name: default
    description: Default
    pipeline:
      pipeline:
        path: pipeline/pipeline.yml
      variables:
        path: pipeline/variables.sample.yml
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    ansible:
      stack:
        path: 'stack_yml/vars.yml.sample'
        destination: '($ project $)/stack_yml/($ environment $)/vars.yml'
