version: "2"
use_cases:
- name: cycloid-common
  sections:

- name: default
  sections:
  - name: Stack
    groups:
    - name: Environment and backups
      technologies: [pipeline]
      vars:
        - name: Environment
          description: "In which environment the VM need to be ?"
          key: environment
          widget: dropdown
          type: string
          values: ["Dev", "UAT", "Prod"]

    - name: "Backup policies"
      technologies: [pipeline]
      condition: "environment==Dev"
      vars:
        - name: Backup Policies
          key: backup_policy_name_dev
          type: string
          widget: dropdown
          values:
          - bkgazuvm00y00m15d04h00
          - bkgazuvm00y06m30d03h30

    - name: Application
      technologies: [ansible]
      vars:
        - name: Application name
          description: "Name of the application"
          key: application_name
          widget: simple_text
          type: string
          required: true
          default: cycloidapp

        - name: "Raw"
          description: "extra yaml to write"
          key: raw_params
          widget: text_area
          type: raw
          #default: |+
          #  test: foo

        - name: Using GCP ?
          description: Display GCP options.
          key: use_gcp
          widget: switch
          type: boolean
          default: false

        - name: Using Aiven ?
          description: Display aiven options.
          key: use_aiven
          widget: switch
          type: boolean
          default: false

        - name: Display advanced options
          description: Check to see advanced options to configure your project.
          key: advanced_opt
          widget: switch
          type: boolean
          default: false

    - name: GCP
      technologies: [ansible]
      condition: use_gcp==true
      vars:
        - name: GKE name
          description: "Name of the GKE cluster"
          key: gcp_gke_name
          widget: simple_text
          type: string

        - name: GitOps repo id
          description: "GitOps repo id"
          key: gcp_gitops_repo_id
          widget: simple_text
          type: string

    - name: Aiven
      technologies: [ansible]
      condition: use_aiven==true
      vars:
        - name: Aiven project name
          description: "Name of the Aiven cluster"
          key: aiven_project_id
          widget: simple_text
          type: string


  - name: Advanced (optional)
    groups:
    - name: config-repository
      condition: advanced_opt==true
      technologies: [pipeline]
      vars:
        #- name: "Config repository"
        #  description: "Git repository URL containing the config of the stack."
        #  key: config_git_repository
        #  type: string
        #  widget: cy_crs
        #  default: "git@github.com:cycloidio/cycloid-labs.git"
        #  required: true
        - name: "Config git key"
          description: "SSH key pair to fetch the config Git repository."
          key: config_git_private_key
          type: string
          widget: cy_cred
          default: "((github-labs.ssh_key))"
          required: true
        #- name: "Config branch"
        #  description: "The branch used by the config repository"
        #  key: config_git_branch
        #  widget: cy_branch
        #  type: string
        #  source: config_git_repository
        #  default: "config"
        #  required: true
