# YAML anchors
shared:

  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: registry-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: /usr/bin/merge-stack-and-config
    outputs:
    - name: merged-stack
      path: "merged-stack"

groups:

- name: overview
  jobs:
  - generate-stacks-yml

resource_types:
resources:

# The Terraform stack (will be merged with the config)
- name: git_stack
  icon: github-circle
  type: git
  source:
    uri: ((stack_git_repository))
    branch: ((stack_git_branch))
    paths:
      - ((stack_path))/stack_yml/*

# The Terraform config (will be merged with the stack)
- name: git_config
  type: git
  icon: github-circle
  source:
    uri: ((config_git_repository))
    branch: ((config_git_branch))
    private_key: ((config_git_private_key))
    paths:
      - ((config_path))/*

jobs:

- name: generate-stacks-yml
  serial: True
  serial_groups: [credential]
  build_logs_to_retain: 3
  plan:
  - do:
    - get: git_config
      trigger: true
    - get: git_stack

    - task: merge-stack-and-config
      config:
        <<: *merge-stack-and-config
        inputs:
        - name: git_config
          path: "config"
        - name: git_stack
          path: "stack"
      params:
        CONFIG_PATH: ((config_path))
        STACK_PATH: ((stack_path))/stack_yml

    - task: gen
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: /bin/bash
          args:
          - -ec
          - |
            DIR=${PWD}
            ansible localhost --connection local -m template -a "src=${DIR}/merged-stack/stack.yaml.j2 dest=${DIR}/merged-stack/stack.yaml" -e @${DIR}/merged-stack/vars.yml
            curl -F file=@${DIR}/merged-stack/stack.yaml https://pastefile.owl.cycloid.io;
        inputs:
          - name: merged-stack
        params:
          ENV: ((env))
          ORG: ((organization))
