# Use the latest version 2 of the Cycloid StackForms engine.
version: 2

# Define the stack configuration form and organize inputs of various types into sections and groups.
# See: https://docs.staging.cycloid.io/deploy/stackforms/file-format.html
use_cases:
- name: aws
  sections:
  - name: pipeline
    groups:
    - name: pipeline
      technologies: [pipeline]
      vars:
        - name: "Cronjobs definitions"
          description: |-
            Aws doc [here](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-cron-expressions.html). Example:
            ```
            test:
              cpu: 256
              memory: 1024
            ```
          key: module.app.cronjobs
          widget: text_area
          type: map
          default:
            test:
              cpu: 256
              memory: 1024

  - name: terraform
    groups:
    - name: terraform
      technologies: [terraform]
      vars:
        - name: "Cronjobs definitions"
          description: |-
            Aws doc [here](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-cron-expressions.html). Example:
            ```
            quiz:
              cpu: 256
              memory: 1024
              entrypoint: "/bin/php"
              schedule: "*/30 * * * ? *"
              cmd: "/var/www/html/app/bin/console app:quiz:reset"
            ```
          key: module.app.cronjobs
          widget: text_area
          type: map
          default:
            quiz:
              cpu: 256
              memory: 1024
              entrypoint: "/bin/php"
              schedule: "*/30 * * * ? *"
              cmd: "/var/www/html/app/bin/console app:quiz:reset"
