version: "2"
use_cases:
- name: cycloid-common
  sections:

- name: default
  sections:
  - name: Stack
    groups:
    - name: Application
      technologies: [ansible]
      vars:
        - name: Application name
          description: "Name of the application"
          key: application_name
          widget: simple_text
          type: string
          required: true
          default: cycloidapp

        - name: "Raw"
          description: "extra yaml to write"
          key: raw_params
          widget: text_area
          type: raw
          default: |+
            # Specific plugin config
