# Use the latest version 2 of the Cycloid stack engine.
version: 2
name: stack-flo-alchemy
canonical: stack-flo-alchemy
author: 'florian'
# Fill in the stack details.
description: 'The bare minimum files to build your stack from scratch.'
image: https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png
template: false
status: 'private'
keywords:
  - 'cycloid'
  - 'test'
  - 'alchemy'
config:
  default:
    name: 'Default'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      onprem:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
