version: "2"
use_cases:
- name: default
  sections:
  - name: Example section
    groups:
    - name: terraform
      technologies: [terraform]
      vars:
      - widget: text_area
        type: array
        name: cronjobs declaration
        required: false
        key: app_cronjobs
        default:
                - id: job-1
                  installed: true
                  name: validationreminder
                  suspend: false
                  schedule: "0 0-23/2 * * *"
                  command: "bin/console validation:remind"
                - id: job-2
                  installed: true
                  name: cleanusers
                  suspend: true
                  schedule: "30 3 * * 2"
                  command: "bin/maintenance clean:user --inactivity_period 365 --grace_duration 7 --max_relances 1 --remove_basket --dry-run"
                - id: job-3
                  installed: false
                  name: apilogclean
                  suspend: false
                  schedule: "* 5 * * 5"
                  command: "bin/maintenance clean:ApiLogs --help"
                - id: job-4
                  installed: false
                  name: workerjobclean
                  suspend: false
                  schedule: "* 4 * * 3"
                  command: "bin/maintenance clean:WorkerRunningJob --help"
    - name: pipeline
      technologies: [pipeline]
      vars:
      - widget: text_area
        type: raw
        name: cronjobs declaration
        required: false
        key: app_cronjobs_pp
        default: |+
                - id: job-1
                  installed: true
                  name: validationreminder
                  suspend: false
                  schedule: "0 0-23/2 * * *"
                  command: "bin/console validation:remind"
                - id: job-2
                  installed: true
                  name: cleanusers
                  suspend: true
                  schedule: "30 3 * * 2"
                  command: "bin/maintenance clean:user --inactivity_period 365 --grace_duration 7 --max_relances 1 --remove_basket --dry-run"
                - id: job-3
                  installed: false
                  name: apilogclean
                  suspend: false
                  schedule: "* 5 * * 5"
                  command: "bin/maintenance clean:ApiLogs --help"
                - id: job-4
                  installed: false
                  name: workerjobclean
                  suspend: false
                  schedule: "* 4 * * 3"
                  command: "bin/maintenance clean:WorkerRunningJob --help"

      - name: Pluginslaunc
        technologies: [pipeline]
        vars:
        - name: "Configurations"
          description: "Content of the configmap used by plugins"
          key: plugins_configuration
          widget: text_area
          type: raw
          required: false
          default: |+
            # Specific plugin config. Can't be empty
