#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#
module "instance" {
  source = "./module-azure"

  azure_location = "${var.azure_location}"

  customer = "${var.customer}"

  env = "${var.env}"

  git_code_commit = "${var.git_code_commit}"

  git_code_repo = "${var.git_code_repo}"

  instance_type = "Standard_DS1_v2"

  project = "${var.project}"

  resource_group_name = "${var.azure_resource_group_name}"

  subnet_id = "/subscriptions/edce4685-4988-4a09-8b4a-3d5b917022cd/resourceGroups/cycloid-demo/providers/Microsoft.Network/virtualNetworks/default/subnets/default"
}
