---

#
# ec2
#
- hosts: tag_role_ec2:&tag_project_{{project}}:&tag_env_{{ env }}:!tag_packer_build_true
  become: yes
  serial: 100%

  vars:
  vars_files:
    - "environments/default_ec2.yml"
    - [ "environments/{{ env }}-ec2", "environments/empty.yml" ]

  roles:
    - role: cycloid.base-aws

  tags:
    - ec2
