---

- hosts: all


  vars_files:
    - "environments/default_variables.yml"
    - [ "environments/{{ env }}-variables.yml", "environments/empty.yml" ]

  tasks:
    - name: Print the message
      ansible.builtin.debug:
        msg: "{{ message_content }}"

    # Terraform outputs are automatically sent as variable to Ansible due to Cycloid scripts
    - name: Display a variable from Terraform outputs
      ansible.builtin.debug:
        msg: "instance_id from Terraform output - {{ instance_id }}"

