---


# - hosts: tag_role_front:&tag_project_{{project}}:&tag_env_{{ env }}:!tag_packer_build_true

- hosts: all
  become: yes

  vars_files:
    - "environments/default_variables.yml"
    - [ "environments/{{ env }}-variables.yml", "environments/empty.yml" ]

  pre_tasks:
    - name: Print the message
      ansible.builtin.debug:
        msg: "{{ message_content }}"

  # roles:
    # - role: cycloid.telegraf
