# YAML anchors
shared:

  # Task : sync and merge with rsync 2 rep. Used to merge stack and config
  - &merge-stack-and-config
    platform: linux
    image_resource:
      type: registry-image
      source:
        repository: cycloid/cycloid-toolkit
        tag: latest
    run:
      path: /usr/bin/merge-stack-and-config
    outputs:
    - name: merged-stack
      path: "merged-stack"

groups:

- name: overview
  jobs:
  - generate-stacks-yml

resource_types:
resources:

jobs:

- name: generate-stacks-yml
  serial: True
  serial_groups: [credential]
  build_logs_to_retain: 3
  plan:
  - do:
    - task: gen
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: cycloid/cycloid-toolkit
            tag: latest
        run:
          path: /bin/bash
          args:
          - -ec
          - |
            DIR=${PWD}
            ls
        params:
          ENV: ((env))
          ORG: ((organization))
