---
# Configuration of the Cycloid stack
version: '2'
name: 'aws-ec2'
canonical: 'stack-aws-ec2'
status: 'private'
description: |
  This stack will deploy a docker image with magento on EC2 instance using default vpc.
keywords:
  - 'aws-ec2'
  - 'provider:aws'
author: 'Cycloid'
image: |
technologies:
  - technology: aws-ec2
    version: n/a

config:
  default:
    name: 'my default use-case'
    description: 'this is the default pipeline of the stack'

    # Configuration of the CI pipeline
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'

    # Configuration of terraform to setup the infrastructure
    terraform:
      aws-ec2:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
