version: "2"
name: testimport
canonical: testimport
author: Florian Lambert
status: private
description: |-
  qdqsdqsdqsdfdsds
  sdfsdf
  sdfsd
image: ""
keywords:
- qsdqs
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      testimport:
        destination: ($ project $)/default/terraform/($ environment $)/testimport.tf
        path: default/terraform/testimport.tf.sample
