#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "lemp" {
  source = "./module-lemp"

  application_ssl_cert = ""
  bastion_sg_allow     = ""
  # WARNING: variable "cloudfront_aliases" (invalid) - couldn't be generated properly
  cloudfront_ssl_certificate = "arn:aws:acm:us-east-1:xxxxxxxx:certificate/xxxxxxx"
  create_cloudfront_medias   = false
  create_elasticache         = true
  create_rds                 = false
  create_s3_medias           = false
  create_ses_access          = false
  customer                   = var.customer
  deploy_bucket_name         = var.deploy_bucket_name
  elasticache_engine_version = "5.0.6"
  elasticache_nodes          = "1"
  elasticache_type           = "cache.t2.micro"
  env                        = var.env
  front_asg_max_size         = 5
  front_count                = "1"
  front_disk_size            = 30
  front_ebs_optimized        = false
  front_type                 = "t3.small"
  keypair_name               = ""
  metrics_sg_allow           = ""
  private_subnets_ids = [
    "subnet-id1",
    "subnet-id2"
  ]
  project = var.project
  public_subnets_ids = [
    "subnet-id1",
    "subnet-id2"
  ]
  rds_backup_retention = 7
  rds_database         = "application"
  rds_disk_size        = 10
  rds_engine_version   = "5.7.16"
  rds_multiaz          = false
  rds_parameters       = "default.mysql5.7"
  rds_password         = var.rds_password
  rds_type             = "db.t3.small"
  rds_username         = "application"
  vpc_id               = "3"
}

