#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "magento" {
  source = "./module-magento"

  bastion_sg_allow           = ""
  customer                   = var.customer
  elasticache_engine_version = "5.0.0"
  elasticache_nodes          = "1"
  elasticache_type           = "cache.t2.small"
  env                        = var.env
  front_count                = "1"
  front_disk_size            = 60
  front_ebs_optimized        = false
  front_type                 = "t3.small"
  keypair_name               = ""
  magento_ssl_cert           = "arn"
  private_subnets_ids = [
    "subnet-id1",
    "subnet-id2"
  ]
  project = var.project
  public_subnets_ids = [
    "subnet-id1",
    "subnet-id2"
  ]
  rds_backup_retention = 7
  rds_database         = "magento"
  rds_disk_size        = 10
  rds_engine_version   = "5.7.16"
  rds_multiaz          = false
  rds_parameters       = ""
  rds_password         = var.rds_password
  rds_type             = "db.t3.small"
  rds_username         = "magento"
  vpc_id               = "123"
}

