#
# This file has been generated by Cycloid, please DO NOT modify.
# Any manual modifications done to this file, WILL be lost on the
# next project edition via the forms.
#
# Please note that comments in sample files will have been dropped
# due to some limitations upon files' generation.
#
# Any extra variables not found in the original file have been ignored.
#

module "prometheus" {
  source = "./module-prometheus"

  aws_region          = var.aws_region
  bastion_sg_allow    = "${data.terraform_remote_state.infrastructure.outputs.infra_bastion_sg_allow}"
  create_rds_database = true
  customer            = var.customer
  enable_https        = false
  env                 = var.env
  keypair_name        = "${data.terraform_remote_state.infrastructure.outputs.keypair_name}"
  private_subnets_ids = [

  ]
  project              = var.project
  prometheus_disk_size = 60
  prometheus_type      = "t3.small"
  public_subnets_ids   = "${data.terraform_remote_state.infrastructure.outputs.infra_public_subnets}"
  rds_database         = "grafana"
  rds_disk_size        = 10
  rds_password         = var.rds_password
  rds_type             = "db.t3.small"
  rds_username         = "grafana"
  vpc_id               = "${data.terraform_remote_state.infrastructure.outputs.infra_vpc_id}"
}

