version: "2"
name: sazdaz
canonical: sazdaz
author: Florian Lambert
status: private
description: sqdqsdqs
image: ""
keywords:
- azdzadaz
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      sazdaz:
        destination: ($ project $)/default/terraform/($ environment $)/sazdaz.tf
        path: default/terraform/sazdaz.tf.sample
