# Configuration of Cycloid stack
---
version: '2'
name: 'kubernetes-test'
canonical: 'stack-kubernetes-test'
description: |
  This stack allows to deploy a chosen kubernetes managed service in one of the available providers.
keywords:
  - 'kubernetes'
  - 'k8s'
  - 'aks'
  - 'provider:azure'
  - 'eks'
  - 'provider:aws'
  - 'gke'
  - 'provider:gcp'
  - 'kapsule'
  - 'provider:scw'
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-kubernetes/master/docs/k8s-logo.png'
technologies:
   - technology: GCP
     version: n/a
   - technology: Azure
     version: n/a
   - technology: AWS
     version: n/a
   - technology: Scaleway
     version: n/a

config:

  # define the default environment for azure
  azure-aks:
    name: 'azure-aks'
    cloud_provider: azurerm
    description: 'Creates Azure K8s Service (AKS) in dedicated VPC with 1+ node pools'
    # Configuration of the CI pipeline
    pipeline:
      pipeline:
        path: 'pipeline/azure-aks.yml'
      variables:
        path: 'pipeline/variables.azure-aks.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    # Configuration of terraform to setup the infrastructure
    terraform:
      aks:
        path: 'terraform/azure-aks/aks.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/aks.tf'
