---
default:
  pipeline:
    Git:
      - name: Config git branch
        key: config_git_branch
        widget: simple_text
        type: string
        description: "Config git branch"
        default:  master
        required: true

      - name: Config git repo
        key: config_git_repository
        widget: simple_text
        type: string
        description: "Config Git repo"
        default: git@github.com:abhaysrivastava-orange/config-all-project-abhay.git
        required: true

    Ansible:
      - name: Bastion url
        key: "bastion_url"
        widget: simple_text
        type: string
        description: "Bastion url"
        default: cloud@90.84.243.183
        required: true
