---
version: '2'
name: 'Ansible test stack'
canonical: 'stack-ansible-test'
description: 'This stack is a dummy stack which contain only a hello world pipeline'
status: 'private'
keywords:
  - 'concourse'
  - 'dummy'
  - 'cycloid'
technologies:
  - technology: concourse
    version: n/a
  - technology: busybox
    version: n/a
author: 'Cycloid'
type: 'stack'
config:
  # define the default pipeline here
  default:
    name: 'AWS ec2 instances'
    description: 'Setup onprem on aws ec2 instances.'
    pipeline:
      pipeline:
        path: 'pipeline/dummy.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    ansible:
      onprem:
        path: 'ansible/cycloid.yml.sample'
        destination: '($ project $)/ansible/cycloid-($ environment $).yml'
