# Configuration of the CI pipeline
name: 'Dummy test stack'
canonical: 'stack-dummy-test'
description: 'This stack is a dummy stack which contain only a hello world pipeline'
keywords:
  - 'concourse'
  - 'dummy'
  - 'cycloid'
technologies:
  - technology: concourse
    version: n/a
  - technology: busybox
    version: n/a
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-dummy/master/icon.png'
type: 'stack'
config:
  # define the default pipeline here
  default:
    name: 'AWS ec2 instances'
    description: 'Setup onprem on aws ec2 instances.'
    pipeline:
      pipeline:
        path: 'pipeline/dummy.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    ansible:
      onprem:
        path: 'ansible/environments/cycloid.yml.sample'
        destination: '($ project $)/ansible/environments/cycloid-($ environment $).yml'
