---
version: '2'
name: ansible-terraform-sample
canonical: ansible-terraform-sample
description: 'bootstrap stack for raw'
# image: https://www.cycloid.io/themes/cycloid/images/owl_logo.png
keywords:
  - 'terraform'
  - 'start'
  - 'sample'
  - 'raw'
  - 'provider:aws'
  - 'provider:azure'
  - 'provider:gcp'
template: true
author: 'GaelL'
technologies:
  - technology: terraform
    version: n/a

config:
  aws:
    name: 'aws'
    description: 'aws pipeline usecase'
    cloud_provider: aws
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'

  azure:
    name: 'azure'
    description: 'azure pipeline usecase'
    cloud_provider: azure
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'

  gcp:
    name: 'gcp'
    description: 'gcp pipeline usecase'
    cloud_provider: gcp
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'

  raw:
    name: 'raw'
    description: 'Standalone pipeline usecase'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
