---
version: '2'
name: terraform-sample
canonical: terraform-sample
description: 'bootstrap stack for raw'
keywords:
  - 'terraform'
  - 'start'
  - 'sample'
  - 'raw'
template: true
author: 'GaelL'
technologies:
  - technology: concourse
    version: n/a
  - technology: terraform
    version: n/a

config:
  default:
    name: 'Default'
    description: 'Default pipeline usecase'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
  aws:
    name: 'aws'
    description: 'aws pipeline usecase'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
