---
version: '2'
name: 'ansible-terraform-sample'
canonical: 'ansible-terraform-sample'
description: |
  this is my dummy stack created
keywords:
  - 'terraform'
  - 'start'
  - 'sample'
  - 'raw'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-dummy/master/icon.png
technologies:
  - technology: concourse
    version: n/a
  - technology: terraform
    version: n/a

config:
  default:
    name: 'Default'
    description: 'Default pipeline usecase'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
