---
version: "2"
use_cases:
- name: raw
  sections:


  - name: App
    groups:
    - name: Instance
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Specify the size of the instance"
        key: instance_type
        widget: auto_complete
        type: string
        values: ["micro","small","medium","large"]
        default: medium
    - name: Ansible config
      technologies: [pipeline]
      vars:
      - name: "Ansible SSH key"
        description: "The SSH key to use when running Ansible to connect on the servers"
        key: ansible_ssh_private_key_pair
        widget: cy_cred
        widget_config:
          display_keys: true
          cred_types:
            - ssh
        type: string
        default: "((ssh.ssh_key))"
        required: true
    - name: Ansible variables
      technologies: [pipeline]
      vars:
      - name: "Message content"
        description: "Fill the Ansible variable message_content"
        key: message_content
        widget: simple_text
        type: string
        default: "Hello from Cycloid"
  - name: Git
    groups:
    - name: config
      technologies: [pipeline]
      vars:
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        widget: cy_cred
        widget_config:
          cred_types:
            - ssh
        #default: "((ssh_config.ssh_key))"
        required: true

    - name: stack
      technologies: [pipeline]
      vars:
      - name: "Stack git key"
        description: "SSH key pair to fetch the stack Git repository."
        key: stack_git_private_key
        type: string
        widget: cy_cred
        widget_config:
          cred_types:
            - ssh
        #default: "((ssh_stack.ssh_key))"
        required: true
